packages:
  - packages/*
  - docs
  - play
  - internal/*

catalog:
  '@vitejs/plugin-vue': ^5.2.1
  '@vitejs/plugin-vue-jsx': ^4.1.1
  'eslint': ^9.22.0
  'prettier': ^3.5.3
  'sass': ^1.85.1
  'typescript': ~5.8.2
  'typescript-eslint': ^8.26.1
  'vite': ^6.2.2
  'vue': ^3.5.13
  'vue-tsc': ^2.2.8
